
### Utilisation de caret

```{r, echo=FALSE}
# install.packages(c('caret', 'e1071'))
library(caret)
```

```{r}
model2 <- train(spam ~ ., data = spambase.train, method = 'glm')
predictions2 <- predict(model2, newdata = spambase.test)
confusionMatrix(predictions2, spambase.test$spam)
```

Avec un arbre de décision:
```{r}
model3 <- train(spam ~ ., data = spambase.train, method = 'rpart')
predictions3 <- predict(model3, newdata = spambase.test)
confusionMatrix(predictions3, spambase.test$spam)

plot(model3$finalModel)
```

Une random forest:
```{r, cache=TRUE}
model4 <- train(spam ~ ., data = spambase.train, method = 'rf')
predictions4 <- predict(model4, newdata = spambase.test)
confusionMatrix(predictions4, spambase.test$spam)

```

Naive Bayes:
```{r, warning=FALSE}
# model5 <- train(spam ~ ., data = spambase.train, method = 'nb')
# predictions5 <- predict(model5, newdata = spambase.test)
# confusionMatrix(predictions5, spambase.test$spam)

```



Pour aller plus loin, introduction au package [caret](http://topepo.github.io/caret/index.html) et tests avec différents algorithmes de machine learning (arbres de décision, random forest, gbm, *Naive Bayes*...)
